image: node:latest
stages:
  - prettier
  - lint
  - test
  - generate-doc

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/
  policy: pull-push


lint:
  stage: lint
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm i
    - npm run lint

prettier:
  stage: prettier
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm i
    - npm run prettier

## lance les tests
test:
  stage: test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm i
    - npm run test
  artifacts:
    paths:
      - jest_html_reporters.html
    name: rapport-test
    when: always
    expire_in: 1 weeks

##  génére la doc en prod
generate-doc:
  stage: generate-doc
  except:
    - schedules
  only:
    - master
    - tags
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm i
    - swagger-jsdoc -d swaggerDef.js -o swagger.json
  artifacts:
    paths:
      - ./docs
    name: doc
    when: always
    expire_in: 1 weeks